services:
  demo:
    build:
      context: .
      args:
        - OPENAI_API_KEY=${OPENAI_API_KEY:-}
        - MCP_SERVER_URLS=${MCP_SERVER_URLS:-}
    env_file:
      - .env
    tty: true
    stdin_open: true